### ISSUE TITLE
npm package is not built for publish

### ISSUE THREAD

**Issue by brianzelip** [primer/primitives#127]
Hi Primer team!

There is no `dist/` directory in the latest npm package.

When I install via `npm i @primer/primitives@v4.3.9` (v4.3.10, or `npm i @primer/primitives`, fails to install), only the source code is there, not the built output. See the contents to the left below:

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/3411019/120812557-17dbc600-c51b-11eb-9e42-cb9dc30f8e0d.png">

Looks like a job for `npm run release`.

Cheers, love the dark dimmed theme!

**Comment by colebemis** [comment]
Interesting. Can you try now? It looks like the dist directory is published: https://unpkg.com/browse/@primer/primitives@4.3.10/dist/

**Comment by brianzelip** [comment]
Yup, https://unpkg.com/@primer/primitives now resolves, and `npm i @primer/primitives` creates the expected package contents in node_modules/.

Did something change, or was it something weird on my end?

**Comment by simurai** [comment]
@brianzelip Yeah, I experienced some weirdness too, see https://github.com/primer/primitives/pull/126#issuecomment-854702157. Not sure, but maybe some npm glitch or it was temporarily down?
