### ISSUE TITLE
NPM Package not found

### ISSUE THREAD

**Issue by KROSF** [primer/primitives#204]
![image](https://user-images.githubusercontent.com/24454660/129441175-4e891aff-c210-4ad7-8fee-2e908371db8b.png)

**Comment by salimzade** [comment]
Same thing. I can't install package

**Comment by GreenSoap** [comment]
I also have this issue

**Comment by tom-ricci** [comment]
Same issue here

**Comment by GreenSoap** [comment]
In the meantime, installing the previous version works fine 
`yarn add @primer/primitives@4.5.4`

If you want the primer/css framework you can use:
`yarn add @primer/css@17.5.1`

**Comment by salimzade** [comment]
I have downloaded tar.gz from cdn js and upacked it un project, fortunately i jus needed a colors json

**Comment by jonrohan** [comment]
We had a problem in our publishing automation. The next patch version should be available. Sorry about that.
