### ISSUE TITLE
Distribution has invalid value for `checks.inputShadow` in dark mode.

### ISSUE THREAD

**Issue by maximedegreve** [primer/primitives#258]
See `checks.inputShadow` in https://unpkg.com/browse/@primer/primitives@5.0.0/dist/json/colors/dark.json
<img width="782" alt="Screenshot 2021-10-18 at 14 09 30" src="https://user-images.githubusercontent.com/980622/137737430-a257583e-d51f-451c-977b-72152065dfc4.png">

**Comment by langermank** [comment]
@simurai did we fix this when we moved it to the dotcom build?

**Comment by simurai** [comment]
👍 Yes, this should now use [`0 0 0 1px var(--color-border-default)`](https://github.com/github/github/blob/1369b50a1df9f48c86ed329c89cfc5fd593a5927/app/assets/stylesheets/bundles/actions/check-colors.scss#L24)
