### ISSUE TITLE
Update repo structure

### ISSUE THREAD

**Issue by lukasoppermann** [primer/primitives#352]
Hey,

with our update to the build process I think we should reconsider the folder structure (I am sure you are thinking the same 😄 )

There are different ways of thinking about this repo. One would be the following:

**This is a design token repo, so the tokens are the product (the main code)**
This means:
1. `src/` holds our tokens as they are the source
2. `dist/` holds our converted tokens
3. `build.ts` is moved to folder `scripts/build.ts`
4. extracted modules (e.g. name conversions, formats, etc. for Style Dictionary) can be placed in a subfolder of root like `libs`, `modules` or `config` (since it is config for SD)

What are your thoughts @rezrah @langermank ?

**Comment by langermank** [comment]
I'm fine with updating the repo structure so long as we don't break any of the old color build in the meantime 😄 we tucked everything away into `tokens` to try and keep some separations between old and new.

**Comment by lukasoppermann** [comment]
We can use a different output folder until we have everything migrated. I will do a PR for the change and we can validate that the output in dist is the same. 👍

**Comment by lukasoppermann** [comment]
Another question is about the desired shape of `dist`.

Do we want to continue with extracting different token types to different files?
- `dist/css/color/...`
- `dist/css/size/...`

Or can we put everything into one file? Of course sizers would be the same across all theme files.
CC: @rezrah @langermank

**Comment by lukasoppermann** [comment]
We and I discuss this and @rezrah will add an ADR proposing the new structure. Once this is done I will start refactoring the structure.
