### ISSUE TITLE
Validation for token files

### ISSUE THREAD

**Issue by lukasoppermann** [primer/primitives#388]
### Describe the bug

Currently the source files `.json5` are not validated which can lead to issues.

The idea to solve this is to use typescript types like this: https://github.com/primer/primitives/blob/design-token-type/%40types/DesignTokenJson.ts and validate the json files against it.

Maybe by using something like [typescript-json-validator](https://www.npmjs.com/package/typescript-json-validator) we can create a validation schema. This could maybe be used with [eslint schema validation](https://ota-meshi.github.io/eslint-plugin-json-schema-validator/).

## Expected results for the validator
- work with `.json5` files
- use typescript types to validate `.json5` files
- validate all `.json5` token and print helpful error messages to console
- checks should if possible:
  - verify the properties names
  - verify properties are not missing
  - verify the values of the properties (at least in part), including custom values (if we get this to work with one example we can later on add validation for more values)

## Stretch
- add this to CI action so that the checks are done for every PR

**Comment by tallys** [comment]
hey @lukasoppermann can this be closed? noticing it's not on any boards

**Comment by lukasoppermann** [comment]
No this is still not done. It is just not highest prio. But @langermank and I could discuss if we really need it. @rezrah worked on this but we never got around finishing it

**Comment by lukasoppermann** [comment]
This was fixed in #692
