### ISSUE TITLE
Improve DX with automated linting

### ISSUE THREAD

**Issue by lukasoppermann** [primer/primitives#412]
Currently it takes some time for the `pre-commit` hook to run, which can degrade the DX during prototyping. 

Solutions would be:

1. Move linting and formatting to pre-push hook

1. Only run select linting and formatting checks on pre-commit (and only on changed / staged files) and reserve entire run for pre-push.

I think I would prefer the second option, would this be fine for you @langermank?

**Comment by langermank** [comment]
Yes, the second option sounds good to me!

**Comment by lukasoppermann** [comment]
Fixed in #484
